In [40]:
#importing libraries
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [41]:
#reading the csv file
df=pd.read_csv("hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [42]:
#preprocessing
#handling null values
df.experience=df.experience.fillna("zero")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [43]:
#converting word to numbers
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [44]:
#handling null values 
#calculate median
import math
median_testscore=math.floor(df['test_score(out of 10)'].median())
median_testscore

8

In [45]:
#filling median in null values
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(median_testscore)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [46]:
#creating object and fitting
reg=linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [47]:
reg.predict(pd.DataFrame({'experience':[2],'test_score(out of 10)':[9],'interview_score(out of 10)':[6]}))

array([53205.96797671])

In [48]:
reg.predict(pd.DataFrame({'experience':[12],'test_score(out of 10)':[10],'interview_score(out of 10)':[10]}))

array([92002.18340611])

In [53]:
#calculating the value for m
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [54]:
#calculating the value for y intercept
reg.intercept_

17737.26346433768

In [55]:
#y=m1*x1+m2*x2+m3*x3+b
2812.95487627*2+1845.70596798*9+2205.24017467*6+17737.26346433768

53205.967976717686

In [56]:
#y=m1*x1+m2*x2+m3*x3+b
2812.95487627*12+1845.70596798*10+2205.24017467*10+17737.26346433768

92002.18340607767